name: proyeccion-rdr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - openpyxl
  - pandas
  - polars
  - pyarrow
  - scikit-learn
  - tabulate
  - holidays
  - pip:
      - python-dotenv
      - mkdocs
      - -e .
